### ISSUE TITLE
Expose list of configured exporters

### ISSUE THREAD

**Issue by LDaneliukas** [QubitProducts/exporter_exporter#15]
## Description
Exporter_exporter currently returns a 404 when accessing its http root. If we look at other exporters, e.g. blackbox_exporter, it might be better to return some information about the endpoints which the exporter can proxy.

## Proposal
Display a list of configured module names that link to `/proxy?module=$name` when accessing `/`. 
PR: #16

**Comment by tcolgate** [comment]
Yep, good idea.

**Comment by tcolgate** [comment]
Closed by #16
