### ISSUE TITLE
Document build process

### ISSUE THREAD

**Issue by frunzales** [QubitProducts/exporter_exporter#18]
I can't find any documentation related to the build process. While the Makefile is pretty explanatory, there's some docker magic that needs to be figured out.

Alternatively, it would be helpful if you'd provide a recent build. The windows binaries don't have support for --web.bearer.token or --web.bearer.token-file.

**Comment by tcolgate** [comment]
I'll look at updating this. In the mean time, I suggest a straight checkout and go build. I'll probably drop the promu usage.

**Comment by tcolgate** [comment]
I've updated to use go modules. If you are using go1.12 you should just be able to go get it now. I also did a release, so hopefully that should fix the windows binary issues.

**Comment by frunzales** [comment]
I was able to successfully build exporter_exporter pre/post your recent commits. I'll submit a pull request with build instructions soon.

**Comment by tcolgate** [comment]
I've simplified the build a little. Gets rid of promu. Also, since we are on go modules now, you should just be able to go get on winodws.

**Comment by tcolgate** [comment]
Also, I pushed out a new release with the windows build included.
