### ISSUE TITLE
Use as library package

### ISSUE THREAD

**Issue by vtolstov** [QubitProducts/exporter_exporter#21]
I have 29 microservices and want to provide it metrics from single endpoint.
Now I'm write some code by hand to get metrics from instances and provide output

**Comment by tcolgate** [comment]
You should probably just use prometheus' target discovery for this.

**Comment by vtolstov** [comment]
i know, but this is not needed, i'm already know ip address of endpoints, that knows about all services. So i want to provide metrics from this endpoints.

**Comment by tcolgate** [comment]
Sorry, I'm not really following what you want to acheive. I'm not opposed to refactoring as a library (it could result in more testable code), but I'm not sure what you are trying to achieve, so am not really sure what the API would look like.

**Comment by tcolgate** [comment]
I'm going to close this for now.
