### ISSUE TITLE
Not an issue - Thanks + Ansible Role

### ISSUE THREAD

**Issue by VoidAndAny** [QubitProducts/exporter_exporter#34]
Thanks for this exporter, it's really useful.

For your information, I released an Ansible role to deploy it.
https://github.com/umanit/ansible-prometheus_exporter_exporter

Yoann

**Comment by tcolgate** [comment]
Thank you, and you are welcome.
I've added a link to your ansible recipe to the README.

**Comment by VoidAndAny** [comment]
👍
