### ISSUE TITLE
[Feature request] Add HTTP basic auth ?

### ISSUE THREAD

**Issue by rdegez** [QubitProducts/exporter_exporter#4]
Hi,

First of all: I was looking for a small & simple, easy to deploy on various system (golang, yeay!), tls-enabled http proxy to secure all prometheus exporter for some time and it your exporter_exporter is doing exactly that! Thanks a lot :-) 
(and the consistency with other prometheus components is very welcome)

I was wondering if you would consider adding basic http-auth to remove the burden of using tls-client cert verification to secure the access to the metrics?

Cheers

**Comment by thomasf** [comment]
I am a bit against this since it more or less encourages unsafe deployments without using encryption at all which isnt a secure access by any standard. If you are using something else for SSL termination you could add the auth there? 

If anything It should be Bearer authentication and not basic.

**Comment by rdegez** [comment]
Even better, thanks a lot!
