### ISSUE TITLE
Returning JSON of modules broken

### ISSUE THREAD

**Issue by LDaneliukas** [QubitProducts/exporter_exporter#44]
It seems that `0.3.1`, or more specifically https://github.com/QubitProducts/exporter_exporter/pull/38 broke the ability to return JSON of all modules and their configuration on request.

Executing `curl -XGET -H "Accept: application/json" localhost:9999` now logs `ERRO[0013] json: unsupported type: func(*http.Request)`

**Comment by tcolgate** [comment]
Right, we're at the point now where I really should ad a test suite.
