### ISSUE TITLE
Switch logger

### ISSUE THREAD

**Issue by thomasf** [QubitProducts/exporter_exporter#5]
I like glog as well, I even have my own fork with some additional stuff but "github.com/prometheus/common/log" should probably be used to behave more like the "stock" exporters.

**Comment by tcolgate** [comment]
This is a fair point, I'll have a think, but it sounds reasonable.

**Comment by tcolgate** [comment]
I've had a very crass go at this. Some stuff that is Info probably wants reclassifying. It'll likely be chattier than glog was

**Comment by thomasf** [comment]
great!
