### ISSUE TITLE
SSL related vulnerabilities 

### ISSUE THREAD

**Issue by vinodmv555** [QubitProducts/exporter_exporter#54]
Hi Team,

Is there any option with exporter_exporter to fix below mentioned vulnerabilities ?

Expecting immediate response . Thanks in advance. 

 1. SSL Version 2 and 3 Protocol detection. 
2. Red Protocal detection. 
3. SSL Medium strength Cipher suites supported (sweet32)

Thanks and Regards,
Vinod M V

**Comment by tcolgate** [comment]
Adjusting the SSL options is a fairly easy update. You can raise a PR to update the minimum protocol version and cipher suites. I'll do it when I get a chance, but cannot provide any time frame. This application, as with all open source tools, is supported under a best effort basis and provides no warranty. Please keep that in mind, and do not demand responses or action to suite your own needs.

**Comment by tcolgate** [comment]
This should be resolved in 0.4.0
