### ISSUE TITLE
params for proxied modules

### ISSUE THREAD

**Issue by tykling** [QubitProducts/exporter_exporter#61]
Hello,

I am trying to use blackbox_exporter which needs among other things a "module" parameter, but I cant figure out how to send it.

README mentions that the /proxy endpoint supports a "params" parameter:

    params (optional): named parameter to pass to the module (either as CLI args, or http parameters).

Is there an example of how to use this somewhere? I tried to find it in the code but I couldn't find anything. Trying it out it seems to only a (list of) strings, not a dict/map, so how does one give a named parameter to the proxied module?

Thanks! :)

**Comment by tcolgate** [comment]
Hi,
  Sorry for the delay in replying. The README was incorrect, it was referring to an old behaviour (before 0.3 I think). The current behaviour is to pass all query string arguments given to the exporter (excluding the first module argument), to the backend. I've updaed the readme to include a specific example for the blackbox exporter, I hope that help.s
