### ISSUE TITLE
Binaries built with a go version containing obsolete mlock kernel issue checks

### ISSUE THREAD

**Issue by gyfis** [QubitProducts/exporter_exporter#64]
Hi, I believe the (latest) v0.4.0 binaries were built with go v1.14.0 that contains old/imprecise checks for a specific kernel issue: https://github.com/golang/go/issues/37436 

When we used the prebuilt binaries on a fresh Ubuntu 20.04 (kernel `5.4.0-65-generic`), the binary crashed after a few minutes with the `mlock` issue described in the `golang/go` thread, even though the kernel is already patched for this issue. When we rebuilt the binaries from source with the latest go (`go1.15.8`), the crashes went away.

I think this can be mitigated by releasing a new version with a more recent go version, or compiling the source manually; I wanted to raise this in case someone else encounters this issue.

Thanks for the exporter!

**Comment by tcolgate** [comment]
Thanks for the heads up, I'll look at pushing ours new build tomorrow.

**Comment by tcolgate** [comment]
0.4.2 is rebuilt with Go 1.15.8, hopefully that resolves your issue.
