### ISSUE TITLE
Support additional metadata

### ISSUE THREAD

**Issue by sebinjohn** [QubitProducts/exporter_exporter#70]
There is already an issue for this here: https://github.com/QubitProducts/exporter_exporter/issues/36. Adding an additional use case for it here.

I have a setup where a host has
- blackbox exporter
- node exporter
- haproxy exporter
- and few other exporters

I also have exporter exporter as a proxy to all the exporters on the host.

the same setup is deployed in dev, staging and production environments.

I see lot of value in adding common properties like "environment" added (as extra metadata) to all the exported metrics. One immediate benefit is that the same prometheus job can be used to scrape from all environments.

**Comment by tcolgate** [comment]
In the prometheus world you would normally uses target scrape relabelling for this purpose. You use some feature of the target discovery you are using to expose a label for your environment, and then use a rewrite rule to add that label to each target. We don't want to do this on expexp for the same reason that all those indididual exporters don't offer the same functionality. It's just not needed in most production deploys.
