### ISSUE TITLE
ARM Release

### ISSUE THREAD

**Issue by steinbrueckri** [QubitProducts/exporter_exporter#73]
Hi *,
I need for a project an ARM release, can you adjust the build and also build an ARM binary on every release?

Cheers 🍻
Richard

**Comment by tcolgate** [comment]
Happy to take a PR, the builds are fiddly enough that I'd need to spend a while testing this so can't loo into it at the moment. Building manually is easy, and cross compiling for arm should just require a `GOARCH=...` . Presumably this is really only useful on linux at the moment?

**Comment by steinbrueckri** [comment]
@tcolgate THX for the fast feedback. I know that I can build for my own but that's not a proper solution, I will do my best to provide a PR. The only place is the Makefile correct? Any other hints from your side?

Cheers 🍻
Richard

**Comment by tcolgate** [comment]
Correct, all the release stuff is in the Makefile. I think it used to rely on some GNU make specific bits, but that may not be the case anymore (been revised a few times).

**Comment by steinbrueckri** [comment]
@tcolgate PR is open, it's not really pretty but it works at least maybe in the future we should take a look at [task](https://taskfile.dev) for an easier and maintainable build system. 😅
