### ISSUE TITLE
Transition option to keep the route for a default module

### ISSUE THREAD

**Issue by anisse** [QubitProducts/exporter_exporter#88]
It's often the case that there's already an exporter in place, and one might want to add another. exporter_exporter has the nice property of listing all the exporters it reverse proxies, listen on a single port, etc.

But at scale, changing the address of all targets from `/metrics` to `/proxy?module=previous-exporter` at the same time is often not feasible. It might be desirable to keep the existing route working during a transition.

Would you be review to a pull request for this ? The goal would be add an option for overriding the `/metrics` and maybe `/` route by the route of a module that is being replaced.

**Comment by tcolgate** [comment]
I'm not quite sure I understand the suggestion (the last sentence isn't quite adding up). Could you show an example config, and what the behaviour would be (how it differs from the current setup).

**Comment by anisse** [comment]
The goal would be to replace `exporter_exporter`'s `/metrics` with a given module. My use case would be to replace an exporter endpoint in-place, transparently, on the same port, before adding more modules.

Before:
 * exporter X (let's say node_exporter), listens on port *:9100
 
After:
 * exporter X listens on 127.0.0.1 port 9100
 * exporter_exporter listens on port 9100. All requests to `/metrics` are treated as if they were requests to `/proxy?module=node`

The config would look like this:
```
modules:
    node:
    method: http
    http:
       address: 127.0.0.1
       port: 9100
transition_module: node
```

Now in my case it's a `collectd`'s `write_prometheus` that I want to replace. Unfortunately this exporter has no router replies with the metrics on any path (!). To be safe I wanted to also replace the `/` route, but this might be erring too much on the side of caution.

I don't know yet what to do with `exporter_exporter`'s own `/metrics` route. Maybe make it available at some other path during the transition.

**Comment by tcolgate** [comment]
TBH this seems very niche. Why not:

- leave existing exporter you are already scraping at a given port /metrics in place
- add exporter_exporter on a different port
- switch scrapes to new port
- once scrapes are all migrated, disable public access to the old default scrape port.

**Comment by tcolgate** [comment]
Perhaps a better options would be for exporter_exporter to allow a default module to be configured, then you could set the `--web.proxy-path=metrics --web.telemetry-path=/expexp_metrics`, and I think you'd get what you want

**Comment by tcolgate** [comment]
v0.5.0 includes the support for a `defaultModule` configuration option. I think that, in combination with the configuration for alternate paths for proxy and telemetry metrics would be enough to achieve your original request.
